### ISSUE TITLE
-lfreetype could not compile?

### ISSUE THREAD

**Issue by RoboMantis** [aochagavia/RusticMineSweeper#1] opened 2015-09-11 16:56 UTC
I had a problem -lfreetype said could not compile?
This was on more than one computer running ubuntu and rust nightly
whats wrong with me!?

**Comment by aochagavia** [comment] 2015-09-12 13:11
Could you provide more details about the error? I am afraid I cannot reproduce it with the information you gave me.

**Comment by RoboMantis** [comment] 2016-05-13 18:44
i was using c9.io It doesn't allow display?

**Comment by aochagavia** [comment] 2016-05-14 08:34
I don't know how c9.io works, but it seems like this problem is related to it. Therefore, I don't think there is anything I can do to fix it (so I am closing this issue).

Feel free to comment below if you manage to solve the problem

**Closed by aochagavia** 2016-05-14 08:34 UTC
